# Generated by Django 3.0.3 on 2020-02-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddle', '0004_auto_20200208_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefrences',
            name='pref_func',
            field=models.CharField(default='no_prefs', max_length=15),
            preserve_default=False,
        ),
    ]
