# Generated by Django 3.0.3 on 2020-02-09 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paddle', '0005_prefrences_pref_func'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedules', models.ManyToManyField(to='paddle.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'first'), (2, 'second')])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='paddle.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='condition_func',
            field=models.CharField(default='no_condition', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='osis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='permissions',
        ),
        migrations.AddField(
            model_name='course',
            name='permissions',
            field=models.ManyToManyField(to='paddle.Permission'),
        ),
        migrations.DeleteModel(
            name='PermissionsList',
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paddle.Semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='paddle.CourseCompletionList'),
        ),
    ]
