# Generated by Django 3.0.3 on 2020-02-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddle', '0006_auto_20200209_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='paddle.Permission'),
        ),
    ]
